# 谜题 36：优柔寡断  

## 背景

 finally 语句块意外结束。

## 代码

下面这个可怜的小程序并不能很好地做出其自己的决定。它的 decision 方法将返回 true，但是它还返回了 false。那么，它到底打印的是什么呢？甚至，它是合法的吗？  

```java
public class Indecisive {
    public static void main(String[] args) {
        System.out.println(decision());
    }

    static boolean decision() {
        try {
            return true;
        } finally {
            return false;
        }
    }
}
```

## 陷阱

你可能会认为这个程序是不合法的，毕竟，decision 方法不能同时返回 true 和false。

如果你尝试一下，就会发现它编译时没有任何错误，并且它所打印的是false。为什么呢？  

## 解惑

在这个程序中，在 try 语句块中的 return 语句所引发的意外结束将被丢弃，而 try-finally 语句意外结束是由 finally 语句块中的 return
造成的。  

**规则**：在一个 try-finally 语句中，**finally 语句块总是在控制权离开 try 语句块时执行的，无论 try 语句块是正常结束的，还是意外结束的情况**都是如此。  

**规则**：**一条语句或一个语句块在finally 语句块抛出了一个异常，或者对某个封闭型语句执行了一个 break 或 continue，或是象这个程序一样在方法中执行了一个return 时，将发生意外结束**。它们之所以被称为意外结束，是因为它们阻止程序去按顺序执行下面的语句。  

**规则**：**当 try 语句块和 finally 语句块都意外结束时，在 try 语句块中引发意外结束的原因将被丢弃，而整个 try-finally 语句意外结束的原因将于 finally 语句块意外结束的原因相同**。  

## 解决办法或规则

**教训**：千万**不要用一个 return、break、continue 或 throw 来退出一个 finally 语句块**，并且千万不要允许将一个受检查的异常传播到一个 finally 语句块之外去。

总之，**每一个 finally 语句块都应该正常结束，除非抛出的是不受检查的异常**。

对于语言设计者，也许应该要求 finally 语句块在未出现不受检查的异常时必须正常结束。朝着这个目标，try-finally 结构将要求 finally 语句块可以正常结束。  